WebApplication8/Models/UtilEntities/Alert.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication8.Models.UtilEntities
{
    public class Alert
    {
        public const string TempDataKey = "TempDataAlerts";

        public string AlertStyle { get; set; }
        public string Message { get; set; }
        public bool Dismissable { get; set; }
    }

    public static class AlertStyles
    {
        public const string Success = "success";
        public const string Information = "info";
        public const string Warning = "warning";
        public const string Danger = "danger";
    }
}

WebApplication8/ViewComponents/CategoryHomeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication8.Data;
using WebApplication8.Models.ShoppingCart;

namespace WebApplication8.ViewComponents
{
    public class CategoryHomeViewComponent : ViewComponent
    {
        private readonly WebShopContext _webc;
        private readonly IShoppingCart shoppingc;
        private readonly ShoppingCart shop;

        public CategoryHomeViewComponent(WebShopContext web, IShoppingCart _shoppingcart, ShoppingCart _shop)
        {
            shoppingc = _shoppingcart;
            shop = _shop;
            _webc = web;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _webc.Categories.Include(u => u.Products).ToListAsync();
            // return PartialView("Partials/_Category", model);
            return View(model);
        }
    }
}

WebApplication8/ViewComponents/HeaderHomeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication8.Data;
using WebApplication8.Models.ShoppingCart;
using WebApplication8.Models.WebShop;

namespace WebApplication8.ViewComponents
{
    public class HeaderHomeViewComponent : ViewComponent
    {
        private readonly WebShopContext _webc;
        private readonly IShoppingCart shoppingc;
        private readonly ShoppingCart shop;

        public HeaderHomeViewComponent(WebShopContext web, IShoppingCart _shoppingcart, ShoppingCart _shop)
        {
            shoppingc = _shoppingcart;
            shop = _shop;
            _webc = web;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cart = shop.Cart();
            try
            {
                var query = await _webc.Categories.Include(u => u.Products).ToListAsync();
                var cat = new List<Category>();
                var BlankCat = new Category() { Id = 0, Name = "All", NameVN = "All" };
                cat.Add(BlankCat);
                var newTable = cat.Union(query);
                ViewBag.Categories = newTable;

            }
            catch { }
            return View(ShoppingCart.Items);
        }
    }
}

WebApplication8/ViewComponents/SaleOffHomeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication8.Data;
using WebApplication8.Models.ShoppingCart;

namespace WebApplication8.ViewComponents
{
    public class SaleOffHomeViewComponent : ViewComponent
    {
        private readonly WebShopContext _webc;
        private readonly IShoppingCart shoppingc;
        private readonly ShoppingCart shop;

        public SaleOffHomeViewComponent(WebShopContext web, IShoppingCart _shoppingcart, ShoppingCart _shop)
        {
            shoppingc = _shoppingcart;
            shop = _shop;
            _webc = web;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _webc.Products.Include(u => u.Category).Include(u => u.Supplier).Where(p => p.Discount > 0).Take(5).ToListAsync();

            // return PartialView("Partials/_Saleoff", model);
            return View(model);
        }
    }
}

WebApplication8/ViewComponents/SpecialHomeViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication8.Data;
using WebApplication8.Models.ShoppingCart;

namespace WebApplication8.ViewComponents
{
    public class SpecialHomeViewComponent : ViewComponent
    {
        private readonly WebShopContext _webc;
        private readonly IShoppingCart shoppingc;
        private readonly ShoppingCart shop;

        public SpecialHomeViewComponent(WebShopContext web, IShoppingCart _shoppingcart, ShoppingCart _shop)
        {
            shoppingc = _shoppingcart;
            shop = _shop;
            _webc = web;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = await _webc.Products.Include(u => u.Category).Include(u => u.Supplier).Where(p => p.Special == true).Take(10).ToListAsync();

            return View(model);
        }

    }
}

WebApplication8/Views/Shared/_Alerts.cshtml
@using WebApplication8.Models.UtilEntities
@using Newtonsoft.Json;
@{
        List<Alert> alerts = new List<Alert>(); ;
        if (TempData.ContainsKey(Alert.TempDataKey))
        {
            var x = (Newtonsoft.Json.Linq.JArray)JsonConvert.DeserializeObject(TempData[Alert.TempDataKey] + "");

            if (x.Any())
            {

                foreach (var alert in x)
                {
                    Alert alert_ = new Alert()
                    {
                     AlertStyle = alert.ElementAt(0).ToString().Replace("\"AlertStyle\":", "").Replace("\"", "").Replace(" ", ""),
                     Message = alert.ElementAt(1).ToString().Replace("\"Message\":", "").Replace("\"", ""),
                     Dismissable = (bool)alert.ElementAt(2)
                     };
                alerts.Add(alert_);
              //  string as_ = alert.ElementAt(0).ToString().Replace("\"AlertStyle\":", "").Replace("\"","");
                //as_.Replace("\"AlertStyle\":", "");

            }

        }

    }
    if (alerts.Any())
    {
        foreach (var alert in alerts)
        {
            var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
            <div class="alert alert-@alert.AlertStyle @dismissableClass" aria-hidden="true" id="id-alert">

                @if (alert.Dismissable)
                {
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                }
                @Html.Raw(alert.Message)
            </div>
        }

    }



}

WebApplication8/Views/Shared/_Layout.cshtml
@using WebApplication8.Models.UtilEntities;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")*@
    @*Styles.Render("~/Unicase/css")*@
    @RenderSection("styles", required: false)
    @Html.Raw(MybundleRegister.AddScript(MybundleRegister.UnicaseCSS, Url.RouteUrl(new { controller = "/" })))
    @*Styles.Render("~/BootstrapValidator/css")*@
    @Html.Raw(MybundleRegister.AddScript(MybundleRegister.BoostrapValidatorCSS, Url.RouteUrl(new { controller = "/" })))
   @*<link href="/Template/User/Unicase/assets/css/blue.css" rel="alternate stylesheet" title="Blue color">
    <link href="/Template/User/Unicase/assets/css/red.css" rel="alternate stylesheet" title="Red color">
    <link href="/Template/User/Unicase/assets/css/orange.css" rel="alternate stylesheet" title="Orange color">
    <link href="/Template/User/Unicase/assets/css/dark-green.css" rel="alternate stylesheet" title="Darkgreen color">

    <link href="/Template/User/Unicase/assets/css/green.css" rel="alternate stylesheet" title="Green color">*@
    <link rel="stylesheet" href="~/Template/User/Unicase/assets/css/font-awesome.min.css">
    @*<link href="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/UnicaseThemes/css")" rel="alternate stylesheet" type="text/css" title="Blue Color" />*@

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' rel='stylesheet' type='text/css'>

    <!-- Favicon -->
    <link rel="shortcut icon" href="/assets/images/favicon.ico">
    @*Scripts.Render("~/bundles/modernizr")*@
    @*@Html.Raw(MybundleRegister.AddScript(MybundleRegister.Modernizr))*@
    @*<script src="/Scripts/ckeditor/ckeditor.js"></script>*@
    <style>
         .table > thead > tr > th,
         .table > tbody > tr > th,
         .table > tfoot > tr > th,
         .table > thead > tr > td,
         .table > tbody > tr > td,
         .table > tfoot > tr > td {
        padding:10px;
        }
    </style>
</head>

<body class="cnt-home">
    @*@Html.Action("Header", "Home")*@
    @await Component.InvokeAsync("HeaderHome")
    <div class="body-content outer-top-xs" id="top-banner-and-menu">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-3 sidebar">
                    @await Component.InvokeAsync("CategoryHome")

                    @await Component.InvokeAsync("SpecialHome")
                    @await Component.InvokeAsync("SaleOffHome")
                    @*
                    *@

                    @*@Html.Action("Category", "Home")
                        @Html.Action("Special", "Home")
                        @Html.Action("SaleOff", "Home")*@
                    @*@Html.Action("ProductTags", "Home")*@
                </div>
                <div class="col-xs-12 col-sm-12 col-md-9 homebanner-holder">
                    @RenderBody()
                </div>
                <input type="hidden" data-urlloadcart="@Url.RouteUrl(new { controller = "Cart", action = "PartialCart" })" id="url_loadcart" />
            </div>
            @*@Html.Action("ListBrand", "Brand")*@
        </div>
    </div>
    @{@await Html.PartialAsync("Partials/_Footer");}
    @{@await Html.PartialAsync("Partials/_boxChat");}

    @*@Scripts.Render("~/Unicase/jquery")*@
    @Html.Raw(MybundleRegister.AddScript(MybundleRegister.UnicaseJS, Url.RouteUrl(new { controller = "/" })))
    <input type="hidden" id="base_url" value="@Url.RouteUrl(new {controller="/" })" />
    <script src="~/lib/signalr/signalr.js"></script>
    <script src="~/Scripts/ChatService/guest_process_chat.js"></script>
    @*@Scripts.Render("~/BootstrapValidator/jquery")*@
    @Html.Raw(MybundleRegister.AddScript(MybundleRegister.BootstrapValidatorJS, Url.RouteUrl(new { controller = "/" })))

    @RenderSection("scripts", required: false)

    <script>
        $(window).bind("load", function () {
            $('.show-theme-options').delay(2000).trigger('click');
        });
    </script>
    <script>
        $(document).ready(function () {
            //   $("#id-alert, #id-error").fadeOut(20000);
            // setTimeout(function () { $("#id-alert").hide() }, 3000)
        });
    </script>
</body>
</html>

WebApplication8/Views/Shared/_ModelPopup.cshtml
<!-- Modal Dialog -->
<div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Delete Parmanently</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure about this ?</p>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirm">Delete</button>
            </div>
        </div>
    </div>
</div>

WebApplication8/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>